### ISSUE TITLE
Insider Rules

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#1]
Können die Insider Trading Rules bei jedem Erwerb durch MA/VR automatisch per Email versandt werden?

**Comment by Nicola8038** [comment]
Was wenn jemand zum zweiten Mal kauft? Ausserdem wissen wir in der Regel nicht im Voraus, ob es sich beim Käufer um einen MA/VR handelt, wenn dieser von Euch nicht kategorisiert wurde. 
Am einfachsten wäre es wenn man die Insiderregeln einmalig an alle MA/VR verschickt und bei neuen MA/VR dies als Beilage zum Arbeitsvertrag zur Verfügung stellt. Was hältst du davon?

**Comment by felivix** [comment]
Gute Erklärung und guter Vorschlag.
