### ISSUE TITLE
Email confirmation messages end up in Spam

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#11]
Several users experienced that the email confirmation mail ended up in their Spam folder.

Is it possible to take steps that this does not happen?

If they can't find the mail is there another way to confirm it?

**Comment by luziusmeisser** [comment]
It would help if they could explicitly mark the messages as "not spam" and complain with their email providers.

From our end, we are fulfilling all the technical requirements.

**Comment by felivix** [comment]
Yes, I did this myself and market all those mails as not spam and also asked this morning the person I guided to do the same (which he did).

Thank you for having taken all preventive measures that it should not happen.
