### ISSUE TITLE
Ticker and Icon

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#13]
Can you provide in the "Inline Variables" the links for Ticker and Icon?

**Comment by pansay** [comment]
you mean "VEDA" and "https://hub.aktionariat.com/images/tokens/VEDA.png" ?

**Comment by felivix** [comment]
Yes, please

**Comment by pansay** [comment]
<var class="akt-ticker"></var>

<img class="akt-icon" style="width: 50px;">

updated

https://hub.aktionariat.com/widgets/

**Comment by felivix** [comment]
Great, thank you
