### ISSUE TITLE
Identity

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#15]
If someone ordered some tokens, payable by bank transfer, is it possible to check if the person also registered his/her personal information? 
I'm asking, because the email address associated with the token order is not revealing who the person might be, so that we could send a personalized reminder.

**Comment by pansay** [comment]
you can already search by e-mail on the shareholders page, but yes we'll also add a link from bank transfers to shareholder page (if registered) to make this easier.

**Comment by felivix** [comment]
Yes, but in this case the person has not yet paid the amount and is therefore not yet a shareholder.
We would like to see everyone registering, even if they have not yet paid for the token.

**Comment by Nicola8038** [comment]
I will open a new issue that proposes a change in the dashboard to support our clients' work in detecting who wants to invest after payment instructions were triggered.
