### ISSUE TITLE
Registration Agreement

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#16]
In the Brokerbot everyone has to click on "I understand that all holders of VEDA tokens are bound to the Token Terms" before they can click on "Send Payment Instructions".

However, we do not have Token Terms, just the Registration Agreement. This is confusing to the users, because they do not know where to find on our website the Token Terms (because they are not there) and wouldn't look for the Registration agreement.

Can we have a link in the Brokerbot directly to the Registration Agreement, like we have one for the Insider Declaration?

**Comment by Nicola8038** [comment]
@bladekp can you have a look into that? I think it's because in the dashboard there is a link pointing to the URL where the token terms are placed. The company can not change this in the dashboard. Thanks in advance.

**Comment by felivix** [comment]
Please create a field where we can enter the URL for the Registration Agreement (others probably would like to link here to their Token Agreement). Like we have it for the the Corporate Trading Rules/Insider Trading Rules.

![image](https://user-images.githubusercontent.com/47902312/151580102-983ecbce-fee0-48da-b06f-dd443cca87e3.png)

**Comment by bladekp** [comment]
I think this is because link you would like to change is stored in blockchain contract, so it is not as easy as changing this in our off ledger db. This is rather the question to the architect how to handle this, I will ask

**Comment by Nicola8038** [comment]
@luziusmeisser How come the Veda Brokerbot has a Token Terms field if they don't have the draggable token? The URL just points to the Veda investors page.

**Comment by Nicola8038** [comment]
@felivix Only the Token Holder Agreement needs to be ticked off by the buyer (not for VEDA because you do not have the draggable contract). The Registration Agreement doesn't need to be ticked off buy the investor, that's why you can just place it on the investor's page.

**Comment by felivix** [comment]
@Nicola8038, this is unfortunately not the case. In the Brokerbot everyone has to click on "I understand that all holders of VEDA tokens are bound to the Token Terms" before they can click on "Send Payment Instructions". Without ticking that box the "Send Payment Instructions" remains greyed out.

**Comment by Nicola8038** [comment]
I know. IMO this is an error, but we need Luzius' opinion on that. :)

--

Nicola Plain

CEO (ad interim)





Aktionariat AG

CHE-453.438.437

Mobile: +41 78 614 83 47

Email: ***@***.***

Web: https://aktionariat.com <http://aktionariat.com>



<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lw3rh45LM6yW1Lvd7b3T1MdDW49M7Pd1Gy6MB0&si=8000000020887941&pi=20e0631b-ea42-42f8-daf7-3deeb10a5eb9>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fQ47l4fGCmnW3Fbt5S3zcKScF43TBFPWrCS1&si=8000000020887941&pi=20e0631b-ea42-42f8-daf7-3deeb10a5eb9>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-4rCvX6W4hCVj23Fbt5SW3F7xMK41RjQSW36dwWw363mD8W3VWt0F4pmP_4W4fxxF_3C36GB0&si=8000000020887941&pi=20e0631b-ea42-42f8-daf7-3deeb10a5eb9>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fdJS31LdWZ2W3T1MdD49M7Pd0&si=8000000020887941&pi=20e0631b-ea42-42f8-daf7-3deeb10a5eb9>


*Aktionariat AG is a company founded by Murat Ögat & Luzius Meisser, a
Swiss Blockchain and Crypto Currency Pioneer. *

*Interested in blockchain? This article could be interesting for you: *Eine
Chance für den Finanzplatz | NZZ
<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-41_40qW3F7smG3K53ntW41S2r143TbcQW41Yx_n3JFWPWW43P1h_3QZmG8W1GzPSM3JF3YjW3zdYNr1GBdn5W49h9zp41n_LcW41PG6b45RjbMW4t3zhP1J7CLKW22WLHc49Kv7ZW3F6hB74fN0QQ0&si=8000000020887941&pi=20e0631b-ea42-42f8-daf7-3deeb10a5eb9>

**Comment by KostasZav** [comment]
@luziusmeisser can you please share your view about this incident?

**Comment by KostasZav** [comment]
With the new brokerbot the users need to click that they have read and agree with the "Investitionsbedingungen" so I guess we can close this ticket.

![image](https://user-images.githubusercontent.com/100678008/214324003-8c28488f-4594-45d7-b133-9ec60781249c.png)
