### ISSUE TITLE
Share Nominal value

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#17]
We can't set the nominal value for our shares. It always reverts back to zero 0

![image](https://user-images.githubusercontent.com/47902312/151579605-9807c6be-9bd0-4af1-bb33-7cda44b9e88f.png)

**Comment by luziusmeisser** [comment]
danke für's melden. sind dran.

**Comment by luziusmeisser** [comment]
habe den fehler gefunden, wird mit dem nächsten dashboard update behoben.
Den Nominalwert habe ich schon mal bei 1 CHF eingesetzt.
