### ISSUE TITLE
Add email address

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#18]
How can we add an email address for a shareholder?

Case 1:
The founding association of AyurVeda AG is listed with its shares but without an email address. 
In an airdrop we now issued them 2 tokens. 
In the shareholder list the association appears now twice, once with the shares, and once with the tokens. 
How to merge the two entries?

Case 2:
A shareholder used a different email address when he bought the shares then now when he lined up for the airdrop. 
He is now listed twice in the shareholder registry.
Can we merge this two accounts? We would like to do that. Or can this only be done by the shareholder?

**Comment by Nicola8038** [comment]
The merge can only be done by the shareholder.

2. To do so the shareholder needs to change the email address in the
Wallet. The company has the possibility to change name and address of the
shareholder but the email address attached to a specific wallet can only be
changes by the shareholder.

1. What kind of wallet do you use for AyurVeda AG? Here it's the same
regarding email address. Check which email address is used for the
non-tokenized shares and make sure that you use the same email address in
the wallet holding the tokenized treasury shares.


--

Nicola Plain

CEO (ad interim)





Aktionariat AG

CHE-453.438.437

Mobile: +41 78 614 83 47

Email: ***@***.***

Web: https://aktionariat.com <http://aktionariat.com>



<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lw3rh45LM6yW1Lvd7b3T1MdDW49M7Pd1Gy6MB0&si=8000000020887941&pi=e5dc8910-a8a1-424b-c206-7114e5b1fdd5>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fQ47l4fGCmnW3Fbt5S3zcKScF43TBFPWrCS1&si=8000000020887941&pi=e5dc8910-a8a1-424b-c206-7114e5b1fdd5>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-4rCvX6W4hCVj23Fbt5SW3F7xMK41RjQSW36dwWw363mD8W3VWt0F4pmP_4W4fxxF_3C36GB0&si=8000000020887941&pi=e5dc8910-a8a1-424b-c206-7114e5b1fdd5>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fdJS31LdWZ2W3T1MdD49M7Pd0&si=8000000020887941&pi=e5dc8910-a8a1-424b-c206-7114e5b1fdd5>


*Aktionariat AG is a company founded by Murat Ögat & Luzius Meisser, a
Swiss Blockchain and Crypto Currency Pioneer. *

*Interested in blockchain? This article could be interesting for you: *Eine
Chance für den Finanzplatz | NZZ
<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-41_40qW3F7smG3K53ntW41S2r143TbcQW41Yx_n3JFWPWW43P1h_3QZmG8W1GzPSM3JF3YjW3zdYNr1GBdn5W49h9zp41n_LcW41PG6b45RjbMW4t3zhP1J7CLKW22WLHc49Kv7ZW3F6hB74fN0QQ0&si=8000000020887941&pi=e5dc8910-a8a1-424b-c206-7114e5b1fdd5>

**Comment by muratogat** [comment]
I think if users would use our wallet app and add/confirm both e-mail addresses there, the accounts would be merged by the backend.

Right @luziusmeisser & @bladekp ?

**Comment by felivix** [comment]
Case 1
The majority share holder is also the initial shareholder who created the company 40+ years ago, before email addresses existed. When I added the initial shareholders to the shareholder registry I used Transfer -> Checkpoint. And I either couldn't or didn't add an email address. How can we add now an email address to majority shareholder?

**Comment by Nicola8038** [comment]
If they hold tokenized shares on a wallet only the shareholders can change
the email. If they only hold non-tokenized shares, the only way to change
this as far as I know would be to make another transfer by choosing
"deletion" and after that add a new "Checkpoint" by creating a new
shareholder incl. email address. Or is there any other way to add the email
address for shareholders holding non-tokenized shares @Murat?

--

Nicola Plain

CEO (ad interim)





Aktionariat AG

CHE-453.438.437

Mobile: +41 78 614 83 47

Email: ***@***.***

Web: https://aktionariat.com <http://aktionariat.com>



<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lw3rh45LM6yW1Lvd7b3T1MdDW49M7Pd1Gy6MB0&si=8000000020887941&pi=2e0982bb-9e8a-44d9-ba8a-693560d64910>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fQ47l4fGCmnW3Fbt5S3zcKScF43TBFPWrCS1&si=8000000020887941&pi=2e0982bb-9e8a-44d9-ba8a-693560d64910>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-4rCvX6W4hCVj23Fbt5SW3F7xMK41RjQSW36dwWw363mD8W3VWt0F4pmP_4W4fxxF_3C36GB0&si=8000000020887941&pi=2e0982bb-9e8a-44d9-ba8a-693560d64910>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fdJS31LdWZ2W3T1MdD49M7Pd0&si=8000000020887941&pi=2e0982bb-9e8a-44d9-ba8a-693560d64910>


*Aktionariat AG is a company founded by Murat Ögat & Luzius Meisser, a
Swiss Blockchain and Crypto Currency Pioneer. *

*Interested in blockchain? This article could be interesting for you: *Eine
Chance für den Finanzplatz | NZZ
<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-41_40qW3F7smG3K53ntW41S2r143TbcQW41Yx_n3JFWPWW43P1h_3QZmG8W1GzPSM3JF3YjW3zdYNr1GBdn5W49h9zp41n_LcW41PG6b45RjbMW4t3zhP1J7CLKW22WLHc49Kv7ZW3F6hB74fN0QQ0&si=8000000020887941&pi=2e0982bb-9e8a-44d9-ba8a-693560d64910>

**Comment by felivix** [comment]
>> If they hold tokenized shares on a wallet only the shareholders can change the email.
Yes, they hold now tokenized shares but this did not help because now we have the same shareholder with two entries, the first one from the Transfer -> Checkpoint without an email address, and now the new entry with the tokenized shares and the email address. I want to merge both entries.

**Comment by felivix** [comment]
It seems I can transfer all the non-tokenized shares to the new entry with the tokenized shares. 

Does this create any problems? Be it in accounting, the shareholder registry and its history, etc.?

**Comment by felivix** [comment]
>>Case 2:
A shareholder used a different email address when he bought the shares then now when he lined up for the airdrop.
He is now listed twice in the shareholder registry.<<

It seems that also in this case I could use Transfer -> Transfer to "merge" the two entries. But I didn't try it yet, since both entries have been entered into the blockchain. But maybe it doesn't matter, because these two entries in the shareholder dashboard are just entries in the Aktionariat database? Correct?

**Comment by felivix** [comment]
> I think if users would use our wallet app and add/confirm both e-mail addresses there, the accounts would be merged by the backend.
> 
> Right @luziusmeisser & @bladekp ?

Yes, correct

**Comment by Nicola8038** [comment]
Case 2: the transfer button is online for off-chain transfers. I think you
can't merge shareholder that only hold tokenized shares.
Case1: If would first delete the existing entry of non-tokenized shares
with the deletion button and after create a "checkpoint" entry to AyurVeda
AG using the correct email address

--

Nicola Plain

CEO (ad interim)





Aktionariat AG

CHE-453.438.437

Mobile: +41 78 614 83 47

Email: ***@***.***

Web: https://aktionariat.com <http://aktionariat.com>



<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lw3rh45LM6yW1Lvd7b3T1MdDW49M7Pd1Gy6MB0&si=8000000020887941&pi=505962d4-fc62-49db-aa68-6bf0e453bacf>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fQ47l4fGCmnW3Fbt5S3zcKScF43TBFPWrCS1&si=8000000020887941&pi=505962d4-fc62-49db-aa68-6bf0e453bacf>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-4rCvX6W4hCVj23Fbt5SW3F7xMK41RjQSW36dwWw363mD8W3VWt0F4pmP_4W4fxxF_3C36GB0&si=8000000020887941&pi=505962d4-fc62-49db-aa68-6bf0e453bacf>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fdJS31LdWZ2W3T1MdD49M7Pd0&si=8000000020887941&pi=505962d4-fc62-49db-aa68-6bf0e453bacf>


*Aktionariat AG is a company founded by Murat Ögat & Luzius Meisser, a
Swiss Blockchain and Crypto Currency Pioneer. *

*Interested in blockchain? This article could be interesting for you: *Eine
Chance für den Finanzplatz | NZZ
<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-41_40qW3F7smG3K53ntW41S2r143TbcQW41Yx_n3JFWPWW43P1h_3QZmG8W1GzPSM3JF3YjW3zdYNr1GBdn5W49h9zp41n_LcW41PG6b45RjbMW4t3zhP1J7CLKW22WLHc49Kv7ZW3F6hB74fN0QQ0&si=8000000020887941&pi=505962d4-fc62-49db-aa68-6bf0e453bacf>

**Comment by felivix** [comment]
Update

Sorry, @Nicola8038, I couldn't resist and tried to merge the two entries in the share holder registry using Transfer - Transfer. And it worked!

To identify the account with the non-tokenized shares I marked it with a preceding underline symbol _
then transferred the non-tokenized shares to the account with the tokenized shares
and the two accounts were merged - now he appears only once on the shareholder list with the correct number of non- and tokenized shares.

Doing this, did I mess up something??
@luziusmeisser 

![image](https://user-images.githubusercontent.com/47902312/151937117-7e2aaeb6-7f3f-433c-97ec-3552e2e77947.png)

![image](https://user-images.githubusercontent.com/47902312/151934907-a7972845-365a-466c-9085-36d3389566f3.png)

![image](https://user-images.githubusercontent.com/47902312/151935944-78c4379b-aeae-4f52-b385-9aebc27c7500.png)

**Comment by felivix** [comment]
Did someone reverse this?
![image](https://user-images.githubusercontent.com/47902312/152020055-3f95f23f-baec-4a6d-a162-0a9f97dbe44b.png)

I's now showing without the 2 Tokens that we transferred to him:
![image](https://user-images.githubusercontent.com/47902312/152019946-dc8146d8-d3d9-4d57-b91c-e5548724a097.png)

**Comment by luziusmeisser** [comment]
Klaus Galler hatte die Adresse nicht registriert. Habe es nun für ihn gemacht.
