### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#22]
On our websites https://veda.ch/investors/ the widgets do not display properly:
- Funding Progress of VEDA - the growing bar is not displaying
- Historic Market Prices of VEDA - is not displaying at all
 
On my test server with the same code I do not experience the same issues
https://veda-token.w3spaces.com/ 

On our WordPress site https://veda.ch/investors/ we do not include the script code in the header, but embed it in the body. Could this be the reason?

**Comment by felivix** [comment]
It seem embedding the script code in the body instead of the head causes the problem.
Are you aware if there is a way to successfully embed the script code in the body?

**Comment by felivix** [comment]
Our webmaster writes me that he gets the following error from the script "widgets-ext.js"
"Unhandled promis rejection: ReferenceError: Can't find variable: Highcharts" 
hub.aktionariat.com is loading widgets-ext.js.

**Comment by pansay** [comment]
fixed now

**Comment by felivix** [comment]
Thanks
