### ISSUE TITLE
Company logo in smart contract

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#26]
Is it possible to include the IPFS hash of the VEDA token logo in our smart contract?

If not, would it make sense for future contracts to include a state variable that would hold an IPFS hash?

**Comment by Nicola8038** [comment]
I think this is a question for you @luziusmeisser

**Comment by luziusmeisser** [comment]
It would be technically possible in future contracts. However, it does not make much sense to do it until there is a standard.
