### ISSUE TITLE
Spacing and font size of Token Events Widget

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#5]
Can you adjust the spacing above the Token Events Widget and the font size so that it matches the other widgets?

![image](https://user-images.githubusercontent.com/47902312/149626371-913a6445-6591-4234-8851-96d5b9c1169f.png)

**Comment by pansay** [comment]
for the spacing I don't think it's on our side, this is what the widgets look like without any extra styling:

https://hub.aktionariat.com/widgets/demo/index-raw.html

**Comment by felivix** [comment]
I see. 
We used <akt-subscribe class="apps" ticker="VEDA"></akt-subscribe>
But now with <akt-subscribe ticker="VEDA" lang="en"></akt-subscribe>
it is OK.

The font size is still considerably larger than in the other widgets.

**Comment by pansay** [comment]
font-size fixed

**Comment by felivix** [comment]
Great! Thank you.

**Comment by muratogat** [comment]
@pansay could we make 2 changes for better integration, also on our website:
- "inputClass" parameter, acting on the input field, just as we are using "buttonClass" parameter currently (with some defaults). This would let anyone configure both fields eternally as they wish.
- Disable automatic centering of this widget. I think the integrator can choose how to position it and put it in a centering div if required.

Thanks

**Comment by pansay** [comment]
ok, updated
