### ISSUE TITLE
Subscribe Widget

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#6]
Kann das Subscribe Widget so konfiguriert werden, dass es rechtsbündig mit den anderen Widgets ist?
Der Button Subscribe to Token Events könnte auch unterhalb der E-Mail Box liegen, wie bei den andern Widgets.

![image](https://user-images.githubusercontent.com/47902312/149631631-3faf99de-967e-4c35-999f-9ba3c29a7750.png)

**Comment by pansay** [comment]
for customizations such as these you can always add your own css, e.g.

![image](https://user-images.githubusercontent.com/4820218/149632754-083be45f-8347-480e-a650-3e7cab3cff2a.png)



akt-subscribe > div {
  text-align:right;
}

akt-subscribe form {
 width: 300px;
 margin-left: 200px
}

akt-subscribe input {
  margin-right: 0;
  margin-bottom: 10px;
  width: 199px;
}

**Comment by felivix** [comment]
I tried it but it doesn't look the same on a mobile and a desktop ....
When it looks sort of good on the desktop, on the mobile it is almost unusable

I reverted back to the way it was before. It is usable on the mobile and not too bad on the desktop.
