### ISSUE TITLE
Inline variables for AyurVeda AG

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#8]
How do we configure the Inline Variables so that the correct data for AyurVeda AG is displayed?
Right now the data it displays on our test page https://veda-token.w3spaces.com/index.html are the ones from Aktionariat AG.

![image](https://user-images.githubusercontent.com/47902312/149658309-1ea760a6-a572-4823-be64-3c6a786d0322.png)

**Comment by muratogat** [comment]
This is the related line in your page:
<script src="https://hub.aktionariat.com/widgets/widgets-ext.js" async="" onload="loadTokenData('DAKS')"></script>
Please change DAKS here to VEDA. All inline variables get their data from the loaded token.

**Comment by felivix** [comment]
Thanks. I just did it.
